        <ul class="breadcrumb">
            <li class="active"><?php echo $this->translate('Overview'); ?></li>
        </ul>
        <div class="row">
            <div class="span8">
                <h1><?php echo $this->translate('Overview'); ?></h1>
                <h4><?php echo $this->translate('Next available episodes'); ?>:</h4>
<?php if( count($this->availableEpisodes) == 0 ): ?>
                <div class="alert">
                    <strong><?php echo $this->translate('Warning'); ?>!</strong> <?php echo $this->translate('You have no favourites yet! Why not add some?'); ?>
                </div>
<?php else: ?>
                <table id="overviewTableNextAvailableEpisodes" class="table table-hover table-condensed table-striped">
                    <thead>
                        <tr>
                            <th style="width:300px;"><?php echo $this->translate('Show'); ?></th>
                            <th><?php echo $this->translate('Season'); ?></th>
                            <th><?php echo $this->translate('Episode'); ?></th>
                            <th><?php echo $this->translate('Availability'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
<?php foreach( $this->availableEpisodes as $directory => $episode ): ?>
                        <tr>
                            <td><a href="<?php echo $this->url(array('directory' => $directory), 'show'); ?>"><?php echo $episode->getShow()->getTitle(); ?></a></td>
                            <td><?php echo $episode->getSeasonNumber(); ?></td>
                            <td><?php echo $episode->getEpisodeNumber(); ?></td>
<?php if( $episode->isAired() && !$episode->isToday() ): if( $episode->isViewed($this->user) ): ?>
                            <td><a data-directory="<?php echo $directory; ?>" data-number="<?php echo $episode->getNumber(); ?>" style="cursor:pointer;"><span class="label label-warning"><?php echo $this->translate('Viewed'); ?></span></a></td>
<?php else: ?>
                            <td><a data-directory="<?php echo $directory; ?>" data-number="<?php echo $episode->getNumber(); ?>" style="cursor:pointer;"><span class="label label-success"><?php echo $this->translate('Available'); ?></span></a></td>
<?php endif; elseif( $episode->isToday() ): ?>
                            <td><a data-directory="<?php echo $directory; ?>" data-number="<?php echo $episode->getNumber(); ?>" style="cursor:pointer;"><span class="label label-info"><?php echo $this->translate('Today'); ?></span></a></td>
<?php else: ?>
                            <td><a data-directory="<?php echo $directory; ?>" data-number="<?php echo $episode->getNumber(); ?>" style="cursor:pointer;"><span class="label label-inverse"><?php echo (is_null($episode->isAired()) ? $this->translate('Unaired') : $episode->daysUntilAirdate() . ' ' . $this->translate('days left')); ?></span></a></td>
<?php endif; ?>
                        </tr>
<?php endforeach; ?>
                    </tbody>
                </table>
<?php endif; ?>
            </div>
            <div class="span4">
                <ul class="nav nav-list">
                    <div class="affix-top" data-spy="affix">
                        <li class="nav-header"><?php echo $this->translate('Quick Search'); ?></li>
                        <li><input type="text" id="search" data-provide="typeahead" autocomplete="off" class="input-medium search-query"></li>
                    </div>
                    <li style="margin-top:9px;" class="nav-header"><?php echo $this->translate('Favourites'); ?></li>
<?php if( count($this->favourites) == 0 ): ?>
                    <div class="alert">
                        <strong><?php echo $this->translate('Warning'); ?>!</strong> <?php echo $this->translate('You have no favourites yet! Why not add some?'); ?>
                    </div>
<?php endif; ?>
<?php foreach( $this->favourites as $favourite ): ?>
                    <li><a href="<?php echo $this->url(array('directory' => $favourite->getDirectory()), 'show'); ?>"><i class="icon"></i> <?php echo $favourite->getTitle(); ?></a></li>
<?php endforeach; ?>
                    <li class="nav-header"><?php echo $this->translate('Account'); ?></li>
                    <li><a href="#modalSettings" data-toggle="modal"><i class="icon icon-user"></i> <?php echo $this->translate('Settings'); ?></a></li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/index/signout"><i class="icon icon-off"></i> <?php echo $this->translate('Sign out'); ?></a></li>
                    <li class="nav-header"><?php echo $this->translate('Other'); ?></li>
                    <li><a href="#modalFeedback" data-toggle="modal"><i class="icon icon-heart"></i> <?php echo $this->translate('Give feedback or suggestions'); ?></a></li>
                    <li><a href="#modalHelp" data-toggle="modal"><i class="icon icon-question-sign"></i> <?php echo $this->translate('Get some help'); ?></a></li>
                </ul>
            </div>
        </div>
