        <ul class="breadcrumb">
            <li><a href="<?php echo $this->baseUrl(); ?>/"><?php echo $this->translate('Overview'); ?></a> <span class="divider">/</span></li>
            <li class="active"><?php echo $this->show->title; ?></li>
        </ul>
        <div class="row">
            <div class="span8">
                <h1><?php echo $this->show->title; ?></h1>
<?php if( !is_null($this->next) ): $episode = $this->next; $directory = $this->show->directory; ?>
                <h4><?php echo $this->translate('Next available episode'); ?>:</h4>
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th style="width:30px;">#</th>
                            <th><?php echo $this->translate('Season'); ?></th>
                            <th><?php echo $this->translate('Episode'); ?></th>
                            <th style="width:280px;"><?php echo $this->translate('Title'); ?></th>
                            <th style="width:80px;"><?php echo $this->translate('Availability'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><?php echo $episode->number; ?></td>
                            <td><?php echo $episode->season; ?></td>
                            <td><?php echo $episode->episode; ?></td>
                            <td><?php echo $episode->title; ?></td>
                            <td><?php if( !isset($episode->aired) ) echo '<span class="label label-inverse">' . $this->translate('Unaired') . '</span>'; else echo ($episode->aired ? '<a href="' . $this->baseUrl() . '/index/markviewed/directory/' . $directory . '/number/' . $episode->number . '"><span class="label label-success">' . $this->translate('Available') . '</span></a>' : ($episode->today ? '<span class="label label-info">' . $this->translate('Today') . '</span>' : '<span class="label label-inverse">' . $episode->daysUntilAired . ' ' . $this->translate('days left') . '</span>')); ?></td>
                        </tr>
                    </tbody>
                </table>
<?php endif; ?>
                <h4><?php echo $this->translate('All episodes'); ?>:</h4>
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th style="width:30px;">#</th>
                            <th><?php echo $this->translate('Season'); ?></th>
                            <th><?php echo $this->translate('Episode'); ?></th>
                            <th style="width:280px;"><?php echo $this->translate('Title'); ?></th>
                            <th style="width:80px;"><?php echo $this->translate('Availability'); ?></th>
                        </tr>
                    </thead>
                    <tbody>
<?php foreach( new Zend_Config(array_reverse($this->episodes->toArray())) as $episode ): ?>
                       <tr<?php echo ($episode->aired ? ($episode->today ? ' class="info"' : '') : ''); ?>>
                            <td><?php echo $episode->number; ?></td>
                            <td><?php echo $episode->season; ?></td>
                            <td><?php echo $episode->episode; ?></td>
                            <td><?php echo $episode->title; ?></td>
<?php if( $episode->aired && !$episode->today ): if( in_array($episode->number, $this->viewed) ): ?>
                            <td><a href="<?php echo $this->baseUrl(); ?>/index/unmarkviewed/directory/<?php echo $this->show->directory; ?>/number/<?php echo $episode->number; ?>"><span class="label label-warning"><?php echo $this->translate('Viewed'); ?></span></a></td>
<?php else: ?>
                            <td><a href="<?php echo $this->baseUrl(); ?>/index/markviewed/directory/<?php echo $this->show->directory; ?>/number/<?php echo $episode->number; ?>"><span class="label label-success"><?php echo $this->translate('Available'); ?></span></a></td>
<?php endif; endif; if( $episode->aired && $episode->today ): ?>
                            <td><span class="label label-info"><?php echo $this->translate('Today'); ?></span></td>
<?php endif; if( !$episode->aired ): ?>
                            <td><span class="label label-inverse"><?php echo (!isset($episode->aired) ? $this->translate('Unaired') : $episode->daysUntilAired . ' ' . $this->translate('days left')); ?></span></td>
<?php endif; ?>
                        </tr>
<?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="span4">
                <ul class="nav nav-list affix-top" data-spy="affix" data-offset-top="70">
                    <li class="nav-header"><?php echo $this->translate('Quick Search'); ?></li>
                    <li><input type="text" id="search" data-provide="typeahead" autocomplete="off" class="input-medium search-query"></li>
                    <li class="nav-header"><?php echo $this->translate('Favourites'); ?></li>
<?php if( count($this->favourites) == 0 ): ?>
                    <div class="alert">
                        <strong><?php echo $this->translate('Warning'); ?>!</strong> <?php echo $this->translate('You have no favourites yet! Why not add some?'); ?>
                    </div>
<?php endif; ?>
<?php foreach( $this->favourites as $favourite ): ?>
                    <li<?php echo ($this->favourited && $this->show->directory == $favourite->directory ? ' class="disabled"' : ''); ?>><a href="/index/show/directory/<?php echo $favourite->directory; ?>"><i<?php echo ($this->favourited && $this->show->directory == $favourite->directory ? ' class="icon icon-chevron-right"' : ' class=""'); ?>></i> <?php echo $this->index[$favourite->directory]['title']; ?></a></li>
<?php endforeach; ?>
                    <li class="nav-header"><?php echo $this->translate('Actions'); ?></li>
<?php if( !$this->favourited ): ?>
                    <li><a href="<?php echo $this->baseUrl(); ?>/index/favourite/directory/<?php echo $this->show->directory; ?>"><i class="icon icon-plus-sign"></i> <?php echo $this->translate('Add as favourite'); ?></a></li>
<?php else: ?>
                    <li><a href="<?php echo $this->baseUrl(); ?>/index/unfavourite/directory/<?php echo $this->show->directory; ?>"><i class="icon icon-minus-sign"></i> <?php echo $this->translate('Remove from favourites'); ?></a></li>
<?php endif; ?>
                    <li><a href="<?php echo $this->baseUrl(); ?>/index/markallviewed/directory/<?php echo $this->show->directory; ?>"><i class="icon icon-eye-open"></i> <?php echo $this->translate('Mark all as viewed'); ?></a></li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/index/unmarkallviewed/directory/<?php echo $this->show->directory; ?>"><i class="icon icon-eye-close"></i> <?php echo $this->translate('Mark all as available'); ?></a></li>
                    <li class="nav-header"><?php echo $this->translate('Account'); ?></li>
                    <li><a href="#modalSettings" data-toggle="modal"><i class="icon icon-user"></i> <?php echo $this->translate('Settings'); ?></a></li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/index/signout"><i class="icon icon-off"></i> <?php echo $this->translate('Sign out'); ?></a></li>
                    <li class="nav-header"><?php echo $this->translate('Other'); ?></li>
                    <li><a href="#modalFeedback" data-toggle="modal"><i class="icon icon-heart"></i> <?php echo $this->translate('Give feedback or suggestions'); ?></a></li>
                    <li><a href="#modalHelp" data-toggle="modal"><i class="icon icon-question-sign"></i> <?php echo $this->translate('Get some help'); ?></a></li>
                </ul>
            </div>
        </div>
