        <ul class="breadcrumb">
            <li class="active"><?php echo $this->translate('Sign in'); ?></li>
        </ul>
        <div class="row">
            <div class="span8">
                <h1><?php echo $this->title; ?></h1>
                <div id="myCarousel" class="carousel slide">
                    <div class="carousel-inner">
                        <div class="active item">
                            <img src="<?php echo $this->baseUrl(); ?>/img/overview.png" />
                            <div class="carousel-caption">
                                <h4><?php echo $this->translate('EpCtrl.com – over 6000 tv-series'); ?></h4>
                                <p><?php echo $this->translate('EpCtrl has episode lists for over 6000 tv-series.'); ?></p>
                            </div>
                        </div>
                        <div class="item">
                            <img src="<?php echo $this->baseUrl(); ?>/img/show.png" />
                            <div class="carousel-caption">
                                <h4><?php echo $this->translate('EpCtrl.com – control over next available episodes'); ?></h4>
                                <p><?php echo $this->translate('Gives you control over what episodes you\'ve already watched.'); ?></p>
                            </div>
                        </div>
                    </div>
                    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
                </div>
            </div>
            <div class="span4">
                <ul class="nav nav-list">
                    <li class="nav-header"><?php echo $this->translate('Sign in'); ?></li>
                    <li>
<?php if( $this->signinError ): ?>
                        <div class="alert alert-danger">
                            <strong><?php echo $this->translate('Warning'); ?>!</strong> <?php echo $this->humanReadableError; ?>
                        </div>
<?php endif; ?>
                        <form method="POST">
                            <fieldset>
                                <input type="hidden" name="type" value="signin" />
                                <input type="text" name="email" value="<?php echo $this->email; ?>" placeholder="Your email" />
                                <input type="password" name="password" placeholder="Your password" />
                                <button type="submit" class="btn btn-success"><?php echo $this->translate('Sign in'); ?></button>
                            </fieldset>
                        </form>
                    </li>
                    <li class="nav-header"><?php echo $this->translate('Sign up'); ?></li>
                    <li>
<?php if( $this->signupError ): ?>
                        <div class="alert alert-danger">
                            <strong><?php echo $this->translate('Warning'); ?>!</strong> <?php echo $this->humanReadableError; ?>
                        </div>
<?php endif; ?>
                        <form method="POST">
                            <fieldset>
                                <input type="hidden" name="type" value="signup" />
                                <input type="text" name="signupEmail" value="<?php echo $this->signupEmail; ?>" placeholder="Your email" />
                                <input type="password" name="signupPassword" placeholder="Your password" />
                                <input type="password" name="signupPasswordAgain" placeholder="… and again" />
                                <span class="help-block"><?php echo $this->translate('The account will be accessable right away!'); ?></span>
                                <button type="submit" class="btn btn-success"><?php echo $this->translate('… or sign up for free'); ?></button>
                            </fieldset>
                        </form>
                    </li>
                </ul>
            </div>
        </div>
