<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title><?php echo $this->title; ?></title>
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            padding: 60px 20px;
        }
        .hero-unit {
            padding: 30px;
        }
        footer {
            text-align:center;
        }
        .affix-top {
            top: auto;
        }
        .affix {
            top: 40px;
        }
    </style>
</head>
<body>
    <div class="container">
<?php echo $this->layout()->content; ?>
        <hr />
        <footer>
            <p>© Kopibeskyttet av Kristoffer A. Iversen 2013. Alle rettigheter reserverte.</p>
        </footer>
        <div id="modalSettings" class="modal fade hide">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3><?php echo $this->translate('Your user settings'); ?> <i class="icon icon-heart"></i></h3>
            </div>
            <div class="modal-body">
                <div class="accordion" id="accordionSettings">
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionSettings" href="#collapseSettingsOne"><?php echo $this->translate('Account details'); ?></a>
                        </div>
                        <div id="collapseSettingsOne" class="accordion-body collapse in">
                            <div class="accordion-inner">
                                <div class="form-horizontal">
                                    <div class="control-group">
                                        <label class="control-label" for="language"><?php echo $this->translate('Language'); ?></label>
                                        <div class="controls">
                                            <select name="language">
                                                <option value="en-us" selected><?php echo $this->translate('English'); ?></option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="password"><?php echo $this->translate('Password'); ?></label>
                                        <div class="controls">
                                            <input type="password" name="password" placeholder="New password">
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="passwordAgain"><?php echo $this->translate('Password'); ?></label>
                                        <div class="controls">
                                            <input type="password" name="passwordAgain" placeholder="… and again.">
                                        </div>
                                    </div>
                                    <div class="form-actions">
                                        <button type="button" class="btn btn-success"><?php echo $this->translate('Update account'); ?></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionSettings" href="#collapseSettingsTwo"><?php echo $this->translate('Remove account'); ?></a>
                        </div>
                        <div id="collapseSettingsTwo" class="accordion-body collapse">
                            <div class="accordion-inner">
                                <div class="form-horizontal">
                                    <div class="control-group">
                                        <label class="control-label" for="password"><?php echo $this->translate('Password to confirm'); ?></label>
                                        <div class="controls">
                                            <input type="password" name="password" placeholder="You account password">
                                        </div>
                                    </div>
                                    <div class="form-actions">
                                        <button type="button" class="btn btn-danger"><?php echo $this->translate('Remove my account'); ?></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
            </div>
        </div>
        <div id="modalFeedback" class="modal fade hide">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3><?php echo $this->translate('Give us some feedback'); ?> <i class="icon icon-heart"></i></h3>
            </div>
            <div class="modal-body">
<?php if( $this->feedbackError ): ?>
                <div class="alert alert-error">
                    <strong><?php echo $this->translate('Warning'); ?>!</strong> <?php echo $this->humanReadableError; ?>
                </div>
<?php endif; ?>
                <form method="POST">
                    <fieldset>
                        <input type="hidden" name="type" value="feedback" />
                        <input type="text" name="subject" value="<?php echo $this->feedbackSubject; ?>" placeholder="Short and descriptive subject" class="span6" />
                        <textarea name="message" rows="10" class="span6"><?php echo $this->feedbackTextarea; ?></textarea>
                        <span class="help-block"><?php echo $this->translate('Your feedback is important for us to improve. Please let us know what\'s good and what\'s missing.'); ?></span>
                    </fieldset>
                </form>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
                <button onclick="$(this).parent().parent().find('form').submit();" class="btn btn-success"><?php echo $this->translate('Send feedback'); ?></button>
            </div>
        </div>
        <div id="modalHelp" class="modal fade hide">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3><?php echo $this->translate('Need some help?'); ?> <i class="icon icon-exclamation-sign"></i></h3>
            </div>
            <div class="modal-body">
                <div class="accordion" id="accordionHelp">
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionHelp" href="#collapseOne"><?php echo $this->translate('I found a bug, what do I do?'); ?></a>
                        </div>
                        <div id="collapseOne" class="accordion-body collapse in">
                            <div class="accordion-inner">
                                <p><?php echo $this->translate('If you find a bug it\'s important that you let us know so we can fix it! Please use the Feedback form, and mark the subject with «Bug report».'); ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionHelp" href="#collapseTwo"><?php echo $this->translate('I have an idea for a new feature, to whom do I speak?'); ?></a>
                        </div>
                        <div id="collapseTwo" class="accordion-body collapse">
                            <div class="accordion-inner">
                                <p><?php echo $this->translate('If you get a good idea for a new feature you\'d like to see, please let ut know. You could egihter do that by using the feedback form (mark the subject with «Feature idea»), or if you are a developer you can fork (this prosject is opensource and available at github) or contribute to the project.'); ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionHelp" href="#collapseThree"><?php echo $this->translate('How can I contribute?'); ?></a>
                        </div>
                        <div id="collapseThree" class="accordion-body collapse">
                            <div class="accordion-inner">
                                <p><?php echo $this->translate('I welcome you to send us a pull-request if you fix bugs, improve on features or come up with something new :-D. This project is available at github as a open source project. If you want to contribute in some other way, please let me know using the Feedback form.'); ?></p>
                            </div>
                        </div>
                    </div>
                    <div class="accordion-group">
                        <div class="accordion-heading">
                            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordionHelp" href="#collapseFour"><?php echo $this->translate('I have some other problem!'); ?></a>
                        </div>
                        <div id="collapseFour" class="accordion-body collapse">
                            <div class="accordion-inner">
                                <p><?php echo $this->translate('If you have some other problem I welcome you to let us know by using the Feedback form and we\'ll try to get back to you as soon as possible at the email-address of your account.'); ?></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal"><?php echo $this->translate('Close'); ?></button>
            </div>
        </div>
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function() {

            $('#search').typeahead({
                'source': function(query, process) {
                    $.get('<?php echo $this->url(array('action' => 'search'), 'ajax'); ?>', {q:query}, function(data) {
                        return process(data.parameters);
                    });
                },
                'updater': function(item) {
                    window.location = '<?php echo $this->url(array('directory' => ''), 'show'); ?>/' + item;
                }
            });

            var markAsViewed = function() {
                var label = $(this).children('span');
                $(label).removeClass('label-success').addClass('label-warning');
                $(label).html('<?php echo $this->translate('Wait …'); ?>');
                $.get('<?php echo $this->url(array('action' => 'markepisodeviewed'), 'ajax'); ?>', {directory: $(this).data('directory'), number: $(this).data('number')}, function(data) {
                    if( data.status == 200 ) {
                        $(label).html('<?php echo $this->translate('Viewed'); ?>');
                        $(label).parent().removeClass('markAsViewed').addClass('unmarkAsViewed');
                        $(label).parent().unbind('click');
                        $(label).parent().click(unmarkAsViewed);
                    }
                });
            };

            var unmarkAsViewed = function() {
                var label = $(this).children('span');
                $(label).html('<?php echo $this->translate('Wait …'); ?>');
                $.get('<?php echo $this->url(array('action' => 'unmarkepisodeviewed'), 'ajax'); ?>', {directory: $(this).data('directory'), number: $(this).data('number')}, function(data) {
                    if( data.status == 200 ) {
                        $(label).html('<?php echo $this->translate('Available'); ?>');
                        $(label).removeClass('label-warning').addClass('label-success');
                        $(label).parent().unbind('click');
                        $(label).parent().click(markAsViewed);
                    }
                });
            };

            $('a.markAsViewed').click(markAsViewed);
            $('a.unmarkAsViewed').click(unmarkAsViewed);

            var markSeasonAsViewed = function() {
                var label = $(this).children('span');
                $(label).removeClass('label-success').addClass('label-warning');
                $(label).html('<?php echo $this->translate('Wait …'); ?>');
                $.get('<?php echo $this->url(array('action' => 'markseasonviewed'), 'ajax'); ?>', {directory: $(this).data('directory'), number: $(this).data('number')}, function(data) {
                    if( data.status == 200 ) {
                        $(label).html('<?php echo $this->translate('Set none'); ?>');
                        $(label).parent().removeClass('markSeasonAsViewed').addClass('unmarkSeasonAsViewed');
                        $(label).parent().unbind('click');
                        $(label).parent().click(unmarkSeasonAsViewed);
                        $(label).parent().parent().parent().parent().parent().find('tbody a span.label').removeClass('label-success').addClass('label-warning').html('<?php echo $this->translate('Viewed'); ?>');
                        $(label).parent().parent().parent().parent().parent().find('tbody a').unbind('click').click(unmarkAsViewed);
                    }
                });
            };

            var unmarkSeasonAsViewed = function() {
                var label = $(this).children('span');
                $(label).html('<?php echo $this->translate('Wait …'); ?>');
                $.get('<?php echo $this->url(array('action' => 'unmarkseasonviewed'), 'ajax'); ?>', {directory: $(this).data('directory'), number: $(this).data('number')}, function(data) {
                    if( data.status == 200 ) {
                        $(label).html('<?php echo $this->translate('Set all'); ?>');
                        $(label).removeClass('label-warning').addClass('label-success');
                        $(label).parent().unbind('click');
                        $(label).parent().click(markSeasonAsViewed);
                        $(label).parent().parent().parent().parent().parent().find('tbody a span.label').removeClass('label-warning').addClass('label-success').html('<?php echo $this->translate('Available'); ?>');
                        $(label).parent().parent().parent().parent().parent().find('tbody a').unbind('click').click(markAsViewed);
                    }
                });
            };

            $('a.markSeasonAsViewed').click(markSeasonAsViewed);
            $('a.unmarkSeasonAsViewed').click(unmarkSeasonAsViewed);

            $('#collapseSettingsOne').find('button').click(function() {
                var button = this;
                $(button).parent().parent().parent().find('div.alert').remove();
                $.get('<?php echo $this->baseUrl(); ?>/index/ajaxupdatesettings',
                {
                    language: $(this).parent().parent().find('div.control-group select').val(),
                    password: $(this).parent().parent().find('div.control-group input[name=password]').val(),
                    passwordAgain: $(this).parent().parent().find('div.control-group input[name=passwordAgain]').val()
                }, function(data) {
                    if( typeof data != 'object' ) {
                        $(button).parent().parent().parent().prepend('<div class="alert alert-error"><a class="close" data-dismiss="alert" href="#">&times;</a><strong>Failure!</strong> Something went wrong</div>');
                        return;
                    }
                    if( data.error ) {
                        $(button).parent().parent().parent().prepend('<div class="alert alert-error"><a class="close" data-dismiss="alert" href="#">&times;</a><strong>' + data.exclaim + '!</strong> ' + data.humanReadable + '</div>');
                    }else{
                        $(button).parent().parent().parent().prepend('<div class="alert alert-success"><a class="close" data-dismiss="alert" href="#">&times;</a><strong>' + data.exclaim + '!</strong> ' + data.humanReadable + '</div>');
                    }
                });
            });

            $('#collapseSettingsTwo').find('button').click(function() {
                var button = this;
                $(button).parent().parent().parent().find('div.alert').remove();
                $.get('<?php echo $this->baseUrl(); ?>/index/ajaxremoveaccount',
                {
                    password: $(this).parent().parent().find('div.control-group input[name=password]').val()
                }, function(data) {
                    if( typeof data != 'object' ) {
                        $(button).parent().parent().parent().prepend('<div class="alert alert-error"><a class="close" data-dismiss="alert" href="#">&times;</a><strong>Failure!</strong> Something went wrong</div>');
                        return;
                    }
                    if( data.error ) {
                        $(button).parent().parent().parent().prepend('<div class="alert alert-error"><a class="close" data-dismiss="alert" href="#">&times;</a><strong>' + data.exclaim + '!</strong> ' + data.humanReadable + '</div>');
                    }else{
                        window.location = '<?php echo $this->baseUrl(); ?>/';
                    }
                });
            });

<?php if( $this->feedbackError ): ?>
            $('#modalFeedback').modal('show');

<?php endif; ?>
        });
    </script>
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-38190931-1']);
        _gaq.push(['_trackPageview']);
        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</body>
</html>
